### ISSUE TITLE
Problem Layout

### ISSUE THREAD

**Issue by fabiobernardo** [frontendfunn/bulma-css-sample-admin-template#1]
The menu opens in the middle of the screen

![image](https://user-images.githubusercontent.com/13204372/141186173-1c0c6969-b96e-4520-83b8-fd1eb053ad63.png)

**Comment by frontendfunn** [comment]
@fabiobernardo Please Provide more details, or share the repo

**Comment by fabiobernardo** [comment]
Resolved!
